/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RegexApp {
    }
    interface RegexBenchmark {
    }
    interface RegexDocs {
    }
    interface RegexMatcher {
        /**
          * @default 'match'
         */
        "mode": 'match' | 'find';
    }
    interface RegexMonitor {
    }
    interface RegexReplace {
    }
    interface RegexSplit {
    }
}
declare global {
    interface HTMLRegexAppElement extends Components.RegexApp, HTMLStencilElement {
    }
    var HTMLRegexAppElement: {
        prototype: HTMLRegexAppElement;
        new (): HTMLRegexAppElement;
    };
    interface HTMLRegexBenchmarkElement extends Components.RegexBenchmark, HTMLStencilElement {
    }
    var HTMLRegexBenchmarkElement: {
        prototype: HTMLRegexBenchmarkElement;
        new (): HTMLRegexBenchmarkElement;
    };
    interface HTMLRegexDocsElement extends Components.RegexDocs, HTMLStencilElement {
    }
    var HTMLRegexDocsElement: {
        prototype: HTMLRegexDocsElement;
        new (): HTMLRegexDocsElement;
    };
    interface HTMLRegexMatcherElement extends Components.RegexMatcher, HTMLStencilElement {
    }
    var HTMLRegexMatcherElement: {
        prototype: HTMLRegexMatcherElement;
        new (): HTMLRegexMatcherElement;
    };
    interface HTMLRegexMonitorElement extends Components.RegexMonitor, HTMLStencilElement {
    }
    var HTMLRegexMonitorElement: {
        prototype: HTMLRegexMonitorElement;
        new (): HTMLRegexMonitorElement;
    };
    interface HTMLRegexReplaceElement extends Components.RegexReplace, HTMLStencilElement {
    }
    var HTMLRegexReplaceElement: {
        prototype: HTMLRegexReplaceElement;
        new (): HTMLRegexReplaceElement;
    };
    interface HTMLRegexSplitElement extends Components.RegexSplit, HTMLStencilElement {
    }
    var HTMLRegexSplitElement: {
        prototype: HTMLRegexSplitElement;
        new (): HTMLRegexSplitElement;
    };
    interface HTMLElementTagNameMap {
        "regex-app": HTMLRegexAppElement;
        "regex-benchmark": HTMLRegexBenchmarkElement;
        "regex-docs": HTMLRegexDocsElement;
        "regex-matcher": HTMLRegexMatcherElement;
        "regex-monitor": HTMLRegexMonitorElement;
        "regex-replace": HTMLRegexReplaceElement;
        "regex-split": HTMLRegexSplitElement;
    }
}
declare namespace LocalJSX {
    interface RegexApp {
    }
    interface RegexBenchmark {
    }
    interface RegexDocs {
    }
    interface RegexMatcher {
        /**
          * @default 'match'
         */
        "mode"?: 'match' | 'find';
    }
    interface RegexMonitor {
    }
    interface RegexReplace {
    }
    interface RegexSplit {
    }
    interface IntrinsicElements {
        "regex-app": RegexApp;
        "regex-benchmark": RegexBenchmark;
        "regex-docs": RegexDocs;
        "regex-matcher": RegexMatcher;
        "regex-monitor": RegexMonitor;
        "regex-replace": RegexReplace;
        "regex-split": RegexSplit;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "regex-app": LocalJSX.RegexApp & JSXBase.HTMLAttributes<HTMLRegexAppElement>;
            "regex-benchmark": LocalJSX.RegexBenchmark & JSXBase.HTMLAttributes<HTMLRegexBenchmarkElement>;
            "regex-docs": LocalJSX.RegexDocs & JSXBase.HTMLAttributes<HTMLRegexDocsElement>;
            "regex-matcher": LocalJSX.RegexMatcher & JSXBase.HTMLAttributes<HTMLRegexMatcherElement>;
            "regex-monitor": LocalJSX.RegexMonitor & JSXBase.HTMLAttributes<HTMLRegexMonitorElement>;
            "regex-replace": LocalJSX.RegexReplace & JSXBase.HTMLAttributes<HTMLRegexReplaceElement>;
            "regex-split": LocalJSX.RegexSplit & JSXBase.HTMLAttributes<HTMLRegexSplitElement>;
        }
    }
}
